# Generated by Django 5.2.1 on 2025-05-19 17:06

from django.db import migrations


def get_user_manager():
    from user.models import UserManager
    return UserManager()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', get_user_manager()),
            ],
        ),
    ]
